### ISSUE TITLE
v2.0.0 not avalible

### ISSUE THREAD

**Issue by mapx** [gocolly/colly#417] opened 2019-12-13 06:32 UTC
The new version v2.0.0 is unavailable at the moment:

```sh
$ go get -u github.com/gocolly/colly/...
$ go list -m all | grep colly
github.com/gocolly/colly v1.2.0
```

**Comment by asciimoo** [comment] 2019-12-13 13:54
This isn't good. Do you have any idea why?

**Comment by mapx** [comment] 2019-12-14 01:49
The command is run in a project that utilizes go module, a feature I'm not familiar with yet, with `go version go1.13.5`.

https://proxy.golang.org/github.com/gocolly/colly/@v/v1.info tells
`{"Version":"v1.2.0","Time":"2019-02-13T13:16:18Z"}`

While https://proxy.golang.org/github.com/gocolly/colly/@v/v2.info returns
`not found: module github.com/gocolly/colly: no matching versions for query "v2"`

Meta information about v2.0.0 is missing.

**Comment by LeMoussel** [comment] 2019-12-14 08:50
this is confirmed with : https://proxy.golang.org/github.com/gocolly/colly/@v/list

> v1.0.0
> v1.1.0
> v1.2.0

**Comment by asciimoo** [comment] 2019-12-17 13:08
It works for me with go `1.12`:

```
% mkdir tmp & cd tmp
% GOPATH=`pwd` go get -u github.com/gocolly/colly
% cat src/github.com/gocolly/colly/go.mod
module github.com/gocolly/colly/v2
[..]
```

**Comment by leolovenet** [comment] 2019-12-19 02:49
same issue，wait for updating

**Comment by x0rzkov** [comment] 2019-12-22 10:52
same issue here too

**Comment by WGH-** [comment] 2019-12-24 23:32
https://github.com/gocolly/colly/blob/v2.0.0/go.mod

This file is supposed to contain `module github.com/gocolly/colly/v2`, not `module github.com/gocolly/colly` (which is fixed in master: https://github.com/gocolly/colly/commit/b5c8aaed63d4599b58f875403dcf41fa9523eeb0). That's probably the issue.

```
$ go get -v github.com/gocolly/colly/v2@v2.0.0
go: github.com/gocolly/colly/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/gocolly/colly" (and .../v2/go.mod does not exist) at revision v2.0.0
go: error loading module requirements
```

**Comment by ale-ben** [comment] 2019-12-26 19:05
I found this similar topic in the GoLang git: [https://github.com/golang/go/issues/35732](url)

Temporary solved using `go get github.com/gocolly/colly@master`
Still listed as v1.2.1 but it actually is the latest commit

**Comment by sky126** [comment] 2019-12-27 12:42
need release new 2.0.1 version

**Comment by legalimpurity** [comment] 2020-01-01 09:00
hi guys, by when can we fix this?

**Comment by x0rzkov** [comment] 2020-01-01 09:46
@asciimoo I have the same issue :-(

**Comment by asciimoo** [comment] 2020-01-03 00:29
Hopefully it is fixed by a version bump. Could you please test it?

**Closed** 2020-01-03 00:28 UTC

**Comment by LeMoussel** [comment] 2020-01-03 07:21
Sounds good.
>$ go get -u github.com/gocolly/colly/...
>$ cat $GOPATH/src/github.com/gocolly/colly/go.mod
```
module github.com/gocolly/colly/v2

go 1.12

require (
.....
)
```
